/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class MultiClass_SwigJNI {
  public final static native long new_Side__SWIG_0();
  public final static native long new_Side__SWIG_1(int jarg1);
  public final static native int Side_getSideLength(long jarg1, Side jarg1_);
  public final static native void delete_Side(long jarg1);
  public final static native int Polygon_getNumberOfSides(long jarg1, Polygon jarg1_);
  public final static native int Polygon_getPerimeter(long jarg1, Polygon jarg1_);
  public final static native int Polygon_addSide(long jarg1, Polygon jarg1_, long jarg2, Side jarg2_);
  public final static native long new_Polygon();
  public final static native void delete_Polygon(long jarg1);
}
