/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Polygon {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Polygon(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Polygon obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MultiClass_SwigJNI.delete_Polygon(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getNumberOfSides() {
    return MultiClass_SwigJNI.Polygon_getNumberOfSides(swigCPtr, this);
  }

  public int getPerimeter() {
    return MultiClass_SwigJNI.Polygon_getPerimeter(swigCPtr, this);
  }

  public int addSide(Side s) {
    return MultiClass_SwigJNI.Polygon_addSide(swigCPtr, this, Side.getCPtr(s), s);
  }

  public Polygon() {
    this(MultiClass_SwigJNI.new_Polygon(), true);
  }

}
