/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vishal_learning_Main */

#ifndef _Included_com_vishal_learning_Main
#define _Included_com_vishal_learning_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vishal_learning_Main
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vishal_learning_Main_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_vishal_learning_Main
 * Method:    createPolygon
 * Signature: ()Lcom/vishal/learning/Polygon;
 */
JNIEXPORT jobject JNICALL Java_com_vishal_learning_Main_createPolygon
  (JNIEnv *, jobject);

/*
 * Class:     com_vishal_learning_Main
 * Method:    addSideToPolygon
 * Signature: (Lcom/vishal/learning/Polygon;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_vishal_learning_Main_addSideToPolygon
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
