/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class cpp_calcJNI {
  public final static native double getFinalResult(int jarg1, int jarg2, char jarg3);
  public final static native long getAString();
}
