/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class cpp_calc {
  public static double getFinalResult(int a, int b, char c) {
    return cpp_calcJNI.getFinalResult(a, b, c);
  }

  public static SWIGTYPE_p_string getAString() {
    return new SWIGTYPE_p_string(cpp_calcJNI.getAString(), true);
  }

}
