/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_echocat_breakpad4j_stacktrace_Main */

#ifndef _Included_org_echocat_breakpad4j_stacktrace_Main
#define _Included_org_echocat_breakpad4j_stacktrace_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_echocat_breakpad4j_stacktrace_Main
 * Method:    getStackTrace
 * Signature: ([BLjava/lang/String;)Lorg/echocat/breakpad4j/stacktrace/StackTrace;
 */
JNIEXPORT jobject JNICALL Java_org_echocat_breakpad4j_stacktrace_Main_getStackTrace
  (JNIEnv *, jclass, jbyteArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
