/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class StringEx_SwigJNI {
  public final static native void StringEx_addName(long jarg1, StringEx jarg1_, String jarg2);
  public final static native String StringEx_getNameAt(long jarg1, StringEx jarg1_, int jarg2);
  public final static native void StringEx_printAll(long jarg1, StringEx jarg1_);
  public final static native int StringEx_getSize(long jarg1, StringEx jarg1_);
  public final static native long new_StringEx();
  public final static native void delete_StringEx(long jarg1);
}
